version: '3.8'

services:
  backend:
    image: sakhasow/smarttask-backend:1.0
    container_name: smarttask-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: sakhasow/smarttask-frontend:1.0
    container_name: smarttask-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
